# Generated by Django 5.0.1 on 2024-05-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20210727_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='sab_code',
        ),
    ]
